@startuml
class MxModel {
    -MxNDScopedFactory factory;
    -Symbol
    +void close()
}

class MxPredictor<I, O> {
    -NDScopedFactory factory;
    +void close()
}

class TranslatorContext {
    +NDScopedFactory ctxFactory;
    +void close()
}

class MxNDScopedFactory {
    -MxNDScopedFactory parent;
    +MxNDArray create(Pointer);
    MxNDScopedFactory newSubFactory()
    MxNDScopedFactory newSubFactory(Context context)
    void attach(AutoCloseable resource)
    void detach(AutoCloseable resource)
    +void close()
}

class MxNDArray {
    -NDScopedFactory factory;
    -Pointer
    void attach(MxNDScopedFactory factory)
    void detach()
    +void close()
}

class NativeResource {
    -Pointer
    +void close()
}

class Symbol {
    -Pointer
    -NDScopedFactory factory;
    -MxNDArray array
    +void close()
}

MxModel o-- Symbol : aggregation
MxModel o-- MxNDScopedFactory : aggregation
Symbol o-right- MxNDArray : aggregation

MxNDArray --|> NativeResource : extends
Symbol --|> NativeResource : extends


MxNDArray o-right- MxNDScopedFactory : aggregation
MxPredictor o-up- MxNDScopedFactory : aggregation
TranslatorContext o-up- MxNDScopedFactory : aggregation



@enduml
