@startuml
(*) --> "Load Model form model zoo"
--> "Create Predictor"
--> "Inference: predictor.predict(input)"
(*) --> "Prepare input"
"Prepare input" --> "Inference: predictor.predict(input)"
--> "Get prediction result"
--> (*)
@enduml
