name: djlbench
version: '0.17.0'
title: DJL Benhmark
license: Apache-2.0
summary: A machine learning benchmarking toolkit
description: |
  djlbench is a command line tool that allows you to benchmark the
  model on all different platforms for single-thread/multi-thread
  inference performance.

  Currently djlbench support the models from the following framework:
  - PyTorch
  - TensorFlow
  - Apachmark MXNet
  - PaddlePaddle
  - ONNXRuntime
  - TensorRT
  - TensorFlow Lite
  - Neo DLR
  - XGBoost
  - Python

base: core18
grade: stable
confinement: classic

apps:
  djlbench:
    command: benchmark-$SNAPCRAFT_PROJECT_VERSION/bin/benchmark
    environment:
      JAVA_HOME: "$SNAP/usr/lib/jvm/java-11-openjdk-amd64"
      PATH: "$SNAP/bin:$PATH:$SNAP/usr/lib/jvm/java-11-openjdk-amd64/bin"

parts:
  djlbench:
    plugin: gradle
    source: https://github.com/deepjavalibrary/djl.git
    source-tag: v$SNAPCRAFT_PROJECT_VERSION
    gradle-output-dir: extensions/benchmark/build/libs
    gradle-options: [ -Pstaging, ':extensions:benchmark:dT' ]
    override-build: |
      snapcraftctl build
      tar xvf $SNAPCRAFT_PART_BUILD/extensions/benchmark/build/distributions/benchmark-*.tar -C $SNAPCRAFT_PART_INSTALL/
      rm -rf $SNAPCRAFT_PART_INSTALL/jar
